### ISSUE TITLE
api.py

### ISSUE THREAD

**Issue by YojanaGadiya** [cthoyt/cookiecutter-snekpack#11]
Dear @cthoyt,

Can you add a bit of context on what the api.py file should have (similar to the cli.py documentation)? Also, if the api.py file is not needed for certain modules, how do you tweak the current package to omit that file while running the tox?

Thank You.

Regards,
Yojana Gadiya

**Comment by cthoyt** [comment]
In https://github.com/cthoyt/cookiecutter-snekpack/commit/a5493870ea0ef0a9f969ff0747ddff595f9ef399, I added a few notes on this. You shouldn't have to change anything in tox.ini, setup.cfg, or pyproject.ini if you remove or rename this file.

**Comment by YojanaGadiya** [comment]
Thanks. This is perfect!!
