### ISSUE TITLE
tox failing on git actions, but passing locally

### ISSUE THREAD

**Issue by YojanaGadiya** [cthoyt/cookiecutter-snekpack#15]
@cthoyt I am running into Python version incompatibility errors wherein the local tox is running completely fine and picking up Python 3.10, but when running tox via the GitHub actions it picks up Python 3.8 for testing. Any pointers on how I can reproduce/tune the local tox to mimic that of the github actions?

Unfortunately, I am not aware why this behavior is seen as it was working perfectly fine two days back.

**Comment by YojanaGadiya** [comment]
FYI - I am now trying to update the Python version on the test workflow to see if that helps, but I am not sure how and why the error arises.

**Comment by cthoyt** [comment]
I can't help if you don't have a repository to point to

**Comment by YojanaGadiya** [comment]
Never mind, it is an issue I fixed. Looked like the version changed mid-way due to collaborator commits. Apologies for bothering you.
