### ISSUE TITLE
How should the docs be generated ?

### ISSUE THREAD

**Issue by oolonek** [cthoyt/cookiecutter-snekpack#9]
Hi @cthoyt I'd like to use your cookiecutter template. I am wondering how I should generate the docs ?

I see no Makefile like in the original https://github.com/audreyfeldroy/cookiecutter-pypackage. Is this on purpose ? 

I followed https://www.youtube.com/watch?v=lo_g-GbYtaA&ab_channel=CoronaWhy and here you generate the docs dir from scratch through `sphinx-quickstart` thus creating the Makefile. 

Here it feels strange to use `sphinx-quickstart` again since part of the docs files and dirs are already present.

What do you advice to have a simple Makefile such as https://github.com/cthoyt-teaches-reproducibility/iter-together-FINISHED/blob/master/docs/Makefile in the docs dir ? Is this even required ?

**Comment by cthoyt** [comment]
Please check out https://github.com/cthoyt/cookiecutter-snekpack/blob/main/%7B%7Bcookiecutter.package_name%7D%7D/.github/CONTRIBUTING.md#documentation

I’ll have more time later to answer your question in detail. Hopefully this is helpful immediately

**Comment by cthoyt** [comment]
The README file also contains in the "Developer" tab another explanation on how to build and open the docs (https://github.com/cthoyt/cookiecutter-snekpack/tree/main/%7B%7Bcookiecutter.package_name%7D%7D#-building-the-documentation) 

Tox is preferred to Make since it has much nicer syntax and support for python projects. You don't have to do any sphinx quickstart since the structure and configuration for the docs is already part of the cookiecutter

**Comment by cthoyt** [comment]
Also keep in mind that my thoughts on packaging have changed over time, and this repo represents the cumulation of all of that - some of the old videos and tutorials are out of date.

**Comment by oolonek** [comment]
Thanks ! As always should have read in more details ... 

Now their is an issue I couldnt nail when using `tox -e docs` (also happens with `tox -e docs-test`).
Here it is :

```
(base) ➜  test_package tox -e docs
.pkg: install_requires> python -I -m pip install setuptools wheel
.pkg: _optional_hooks> python /Users/pma/mambaforge/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /Users/pma/mambaforge/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /Users/pma/mambaforge/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /Users/pma/mambaforge/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
docs: install_package_deps> python -I -m pip install click more-click more-itertools sphinx sphinx-autodoc-typehints sphinx-automodapi sphinx-click sphinx-rtd-theme tqdm
docs: install_package> python -I -m pip install --force-reinstall --no-deps /Users/pma/Dropbox/git_repos/COMMONS_Lab/test_package/.tox/.tmp/package/1/test_package-0.0.1.dev0.tar.gz
docs: commands[0]> python -m sphinx -W -b html -d docs/build/doctrees docs/source docs/build/html
Running Sphinx v6.2.1
making output directory... done
[autosummary] generating autosummary for: cli.rst, index.rst, installation.rst, usage.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/docs/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 4 source files that are out of date
updating environment: [new config] 4 added, 0 changed, 0 removed
reading sources... [100%] usage                                                                                                                                                           

Warning, treated as error:
/Users/pma/Dropbox/git_repos/COMMONS_Lab/test_package/docs/source/cli.rst:6:Unknown directive type "click".

.. click:: test_package.cli:main
   :prog: test_package
   :show-nested:
docs: exit 2 (2.95 seconds) /Users/pma/Dropbox/git_repos/COMMONS_Lab/test_package> python -m sphinx -W -b html -d docs/build/doctrees docs/source docs/build/html pid=28222
.pkg: _exit> python /Users/pma/mambaforge/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  docs: FAIL code 2 (25.20=setup[22.25]+cmd[2.95] seconds)
  evaluation failed :( (26.13 seconds)
```
This I can reproduce on a fresh cookicutter clone bot on MacOS and Ubuntu. 
I am not very suire to get the reason.

The closest issue I could find is https://itecnote.com/tecnote/sphinx-error-unknown-directive-type-automodule-or-autoclass/ indiciating missing dependencies but here click and sphinx-click are clearly added as required dependencies. 
Would you have an idea here ?

**Comment by oolonek** [comment]
OK I get it !

Actually at the following prompt of the coockiecutter setup
`command_line_interface [True]:` I answered by `T` and not `True` hence the error :)
All good ! Thanks for the hints !

**Comment by oolonek** [comment]
This seems to work https://github.com/cthoyt/cookiecutter-snekpack/pull/10
